config/routes.rb
Build::Application.routes.draw do

  devise_for :admins

  if Rails.env.development?
    mount MailPreview => 'mail_view'
  end

  get "search/new"

  get "errors/not_found"

  get "errors/unacceptable"

  get "errors/internal_error"

  get "errors/unauthorized"

  resources :notifications do
    collection {post :sort}
    get :update_seen, on: :collection
  end

  resources :activity_feed do
    collection {post :sort}
  end

  devise_for :users, :controllers => {:registrations => :registrations, omniauth_callbacks: "users/omniauth_callbacks"} 

  devise_scope :user do
      post 'registrations' => 'registrations#create', :as => 'register'
      post 'sessions' => 'sessions#create', :as => 'login'
      delete 'sessions' => 'sessions#destroy', :as => 'logout'
  end

  get "home/index"
  get "about", to: "home#about"
  get "help", to: "home#help"
  get "documentation_tips", to: "home#documentation_tips"
  get "news", to: "home#news"
  get "mobile", to: "home#mobile"
  get "mobile/request", to: "home#mobile_request"
  get "privacy_policy", to: "home#privacy_policy"
  get "dashboard", to: "home#dashboard"

  match 'contact' => 'contact#new', :as=> 'contact', :via => :get
  match 'contact' => 'contact#create', :as=> 'contact', :via=>:post
  match 'announcements/:id/hide', to: 'home#hide_announcement', as: 'hide_announcement'
  match 'search', to: 'application#search', as: :search

  resources :users, :id => /[A-Za-z0-9\-\_\.\+]+?/ , :format => /json|csv|xml|yaml/ do
     match 'users/:id' => 'users#username'
     get 'validate_username', on: :collection
     get 'validate_email', on: :collection
     get :search, on: :collection
     get 'edit_profile', on: :member
     get :projects, on: :member
     get :favorites, on: :member
     get :collections, on: :member
     get :touch, on: :collection
     member do
      get :follow
      get :unfollow
      get :following
      get :followers
     end
  end

  resources :collections do
    post :add_project, on: :member
    get :projects, on: :member
    get :challenges, on: :collection
    get :search, on: :collection
    get :update_privacy, on: :member
  end

  resources :collectifies do
  end

  resources :categories do
  end

  resources :projects do
     collection {post :sort}
     get :builds, on: :collection
     get :built, on: :collection
     get :featured, on: :collection
     get :search, on: :collection
     get :editTitle, on: :collection
     post :categorize, on: :member
     put :favorite, on: :member
     put :remix, on: :member
     get :embed, on: :member
     get :gallery, on: :member
     get :imageView, on: :member
     get :blog, on: :member
     get :export, on: :member
     get :export_txt, on: :member
     get :update_privacy, on: :member
     get :find_users, on: :collection
     get :add_users, on: :collection
     get :remove_user, on: :collection
     get :check_privacy, on: :collection
     get :log, on: :member
     get :timemachine, on: :member
    resources :steps do
        collection {post :sort}
        resources :comments, :only => [:create, :destroy]
        get :create_branch, on: :collection
        get :reset_started_editing, on: :member
        get :update_ancestry, on: :collection
        get :edit_redirect, on: :collection
        get :get_position, on: :collection
        get :show_redirect, on: :collection
        get :update_new_image, on: :member
        get :mobile, on: :collection
      end
      match "steps/:id" => "steps#number", :as => :number
  end

  resources :images do
     collection {post :sort}
     get :find_image_id, on: :collection
     get :rotate, on: :member
     get :export, on: :member
  end

  resources :charts do
    get :users, on: :collection
    get :users_by_month, on: :collection
    get :steps, on: :collection
    get :steps_by_month, on: :collection
    get :comments, on: :collection
    get :comments_by_month, on: :collection
  end

  get "videos/embed_url" => "videos#embed_url", :as => :video_embed_url
  
  resources :videos do
    post :create_mobile, on: :collection
  end

  resources :sounds do
  end
      
  resources :design_files do
  end

  root :to => 'home#index'

  post "versions/:id/revert" => "versions#revert", :as => "revert_version"

  %w( 404 422 500 ).each do |code|
    get code, :to => "errors#show", :code => code
  end

end

app/models/collection.rb
class Collection < ActiveRecord::Base
  include PublicActivity::Common
  include ActionView::Helpers::SanitizeHelper
  extend FriendlyId
  friendly_id :name, use: [:slugged, :history]

  belongs_to :user, :touch=> true
  default_scope -> { order('updated_at DESC') }
  validates :user_id, presence: true

  has_many :collectifies, :dependent => :destroy
  has_many :projects, :through => :collectifies

  attr_accessible :description, :name, :published, :image, :challenge, :privacy

  mount_uploader :image, CollectionImagePathUploader

  validates :name, presence: true, uniqueness: true

  scope :published, where(:published=>true)

  scope :private_collections, where(:privacy => "private")
  scope :unlisted_collections, where(:privacy => "unlisted")
  scope :public_collections, where(:privacy => "public")

  searchable do
    text :description, :stored => true do
      strip_tags(description)
    end
    boolean :published
  end

  def published?
    published = false
    # collections are published if they have a name and more than 1 project
    if !name.starts_with?("Untitled")
      if projects.public_projects.count > 0
        published = true
      end
    end
    return published
  end

  def challenge?
    self.challenge
  end

  def remove!(project)
    collectifies.where(project_id: project.id).first.delete
    if published?
      update_attributes(:published=>true)
    else
      update_attributes(:published=>false)
    end
  end

  def public?
    self.privacy == "public"
  end

  def private?
    self.privacy == "private"
  end

  def unlisted?
    self.privacy == "unlisted"
  end

  # an array of users that includes the author of the collection and authors of
  # any of the projects in a colelction
  def collection_users
    users = Array.new
    users << self.user
    self.projects.each do |project|
      project.users.each do |user|
        unless users.include? user
          users << user
        end
      end
    end
    return users
  end

end

app/controllers/collections_controller.rb
class CollectionsController < ApplicationController
  before_filter :authenticate_user!, except: [:index, :show, :challenges, :search]

  def index
    @collections = Collection.published.order("updated_at DESC").where(:privacy => "public").page(params[:collections_page]).per_page(9)

    respond_to do |format|
      format.html # index.html.erb
      format.js
      format.json { render :json => @collections }
    end
  end

  # GET /collections/challenges 
  def challenges
    @collections = Collection.published.where(:challenge=>true).order("updated_at DESC").page(params[:collections_page]).per_page(9)
    render :template=>"collections/index"
  end

  # GET /collections/1
  # GET /collections/1.json
  def show
    @collection = Collection.find(params[:id])
    @authorLoggedIn = current_user == @collection.user

    if (@collection.private? && !current_user) || (@collection.private? && @collection.collection_users.include?(current_user) == false)
      respond_to do |format|
        format.html {redirect_to errors_unauthorized_path}
      end
    else
      step_ids = Step.joins(:project => :collectifies).where(collectifies: { collection_id: @collection.id }).pluck(:'steps.id')

      @questions = Question.where(:step_id => step_ids).where(:featured => nil).order("created_at DESC")
      @activities = PublicActivity::Activity.where(:trackable_type => "Step").where("trackable_id" => step_ids).where("key" => "step.create").order("created_at DESC").first(5)
      @contributors = @collection.projects.flat_map {|p| p.users}.uniq

      respond_to do |format|
        format.html {
            if request.path != collection_path(@collection)
                redirect_to @collection, status: :moved_permanently
            end
        }
        format.json { render :json => @collections }
      end

    end
  end

  # GET /collections/new
  # GET /collections/new.json
  def new
    @collection = Collection.new
    respond_to do |format|
      format.html { create }
      format.json { render :json => @collection }
    end
  end

  # GET /collections/1/edit
  def edit
    @collection = Collection.find(params[:id])
    authorize! :edit, @collection
  end

  # POST /collections
  # POST /collections.json
  def create
    @collection = current_user.collections.build(params[:collection])

    # set some default values - set collection value to the number of current collections
    if Collection.where("name like ?", "%Untitled%").count > 0
      count = Collection.where("name like ?", "%Untitled%").order("created_at DESC").first.name.sub('Untitled-Collection-','').to_i + 1
    else
      count = 1
    end
    
    @collection.name = "Untitled-Collection-"+count.to_s()
    @collection.user = current_user
    @collection.challenge = false
    @collection.privacy = "unlisted"

    respond_to do |format|
      if @collection.save
        @collection.update_attributes(:name => "Untitled-Collection-" + @collection.id.to_s)
        format.html { redirect_to @collection }
        format.json { render :json => @collection, :status => :created, :location => @collection }
      else
        format.html { render :action => "new" }
        format.json { render :json => @collection.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /collections/1
  # PUT /collections/1.json
  def update
    @collection = Collection.find(params[:id])
    authorize! :update, @collection

    respond_to do |format|
      if @collection.update_attributes(params[:collection])
        # create a new activity if the project is now published
        if @collection.published?
          # if collection is being published for the first time, add a public activity for it
          if @collection.published == false
            if @collection.unlisted?
              @collection.update_attributes(:privacy => "public")
            end
            @collection.create_activity :create, owner: current_user, primary: true
            # create notifications for the projects that are part of the collection
            collectifies = Collectify.where(:collection_id => @collection)
            collectifies.each do |collectify|
              if PublicActivity::Activity.where("trackable_type = ? AND trackable_id = ?", "Collectify", collectify.id).blank? 
                  # add public activity
                  collectify.project.users.each do |user|
                    collectify.create_activity :create, owner: current_user, recipient: user, primary: true
                    if current_user != @collection.user and user != @collection.user
                      collectify.create_activity :owner_create, owner: current_user, recipient: @collection.user, primary: true
                    end
                  end
              end
            end
          end
        @collection.update_attributes(:published=>true)
      else
        collectifies = Collectify.where(:collection_id=>@collection)
        collectifies.each do |collectify|
           PublicActivity::Activity.where("trackable_type = ? AND trackable_id = ?", "Collectify", collectify.id).destroy_all 
        end
        PublicActivity::Activity.where("trackable_type = ? AND trackable_id = ?", "Collection", @collection.id).destroy_all
      end

        format.html { redirect_to @collection }
        format.js
        format.json { head :no_content }
      else
        Rails.logger.debug "#{@collection.errors.inspect}"
        format.js { render :action=> "edit"}
        format.html { render :action => "edit" }
        format.json { render :json => @collection.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /collections/1
  # DELETE /collections/1.json
  def destroy
    @collection = Collection.find(params[:id])
    authorize! :destroy, @collection

    collectifies = Collectify.where(:collection_id=>@collection)
    collectifies.each do |collectify|
      PublicActivity::Activity.where("trackable_type = ? AND trackable_id = ?", "Collectify", collectify.id).destroy_all 
    end

    PublicActivity::Activity.where("trackable_type = ? AND trackable_id = ?", "Collection", @collection.id).destroy_all

    @collection.destroy

    respond_to do |format|
      format.html { redirect_to user_path(current_user.username) }
      format.json { head :no_content }
    end
  end

  def add_project
    @collection = Collection.find(params[:id])
    uri = URI(params[:project_url])
    project_id = uri.path.match('\/projects\/\d+\/').to_s.match('\d+').to_s

    if project_id == ""
      project_id = uri.path.split('/').last.to_s # account for users who don't include "steps" at the end
    end

    if project_id != ""
      logger.debug("project_id: #{project_id}")
      @project = Project.find(project_id)

      begin
        # create collectify entry for project
        collectify = @collection.collectifies.create!(:project_id => @project.id)
        
        if @collection.published?
          # if collection is being published for the first time, add a public activity for it
          if @collection.published == false
            @collection.create_activity :create, owner: current_user, primary: true
            @collection.update_attributes(:privacy => "public")
          end

          @project.users.each do |user|
            if user != current_user
              # notify project users that their project has been added to the collection
              @activity = @collection.collectifies.last.create_activity :create, owner: current_user, recipient: user, primary: true
              # create email notifications
              if user.settings(:email).collectify_recipient == true || ( (user.settings(:email).collectify_recipient == false) && (@collection.user == user) )
                Rails.logger.debug("notifying user that their project has been added to a collection")
                NotificationMailer.delay.notification_message(@activity, user)
              end
            end
          end
        
          if current_user != @collection.user && !@project.users.include?(@collection.user)
            # notify the collection owner that someone else has added a project to the collection
            @activity = @collection.collectifies.last.create_activity :owner_create, owner: current_user, recipient: @collection.user, primary: true
            # create email notifications
            if @collection.user.settings(:email).collectify_recipient == true
              Rails.logger.debug("notifying collection owner than a project was added to their collection")
              NotificationMailer.delay.notification_message(@activity, @collection.user)
            end
          end

          @collection.update_attributes(:published=>true)
        end
        @collection.touch

        respond_to do |format|
          format.html { 
            redirect_to collection_path(@collection, :project_id => @project.id)
            flash[:notice] = 'Added ' + @project.title + ' to the collection!' 
          }
          format.json { render :json => @collections }
        end
      rescue ActiveRecord::RecordNotUnique
        respond_to do |format|
          format.html { redirect_to @collection, :alert => 'Project already exists in collection' }
          format.json { render :json => @collections }
        end
      end
    else
      respond_to do |format|
        format.html { redirect_to @collection, :alert => 'Please enter a valid project URL.' }
        format.json { render :json => @collections }
      end
    end
  end

  def search
    @search_term = params[:search]
    @collections = params[:search_results]

    @project_count = params[:project_count] ||= "0"
    @collection_count = params[:collection_count] ||= "0"
    @user_count = params[:user_count] ||= "0"

    if !@collections.nil?
      @collections = @collections
    else
      @collections = []
    end
    @collections_text = params[:search_text]

    if params[:type] == "Challenges"
      filtered_collections = []

app/helpers/collections_helper.rb
module CollectionsHelper
end

app/views/collections/_collection_activity.html.erb
<div class="label label-warning">Questions</div><br>
<% @questions.each do |question| %>
	<span class="collection_question">
		<%= link_to project_steps_path(question.step.project, :step => question.step.id) do %>
			<%= question.description %>
		<% end %>
	</span><br>
	<div class="byline">
		from <%= link_to question.step.project.title, project_steps_path(question.step.project, :step => question.step.id) %>
	</div>
	<hr style="margin: 5px 0px;">
<% end %>

<div class="label label-info">Latest Updates</div>
<br>
<% @activities.each do |activity| %>
	<% if activity.trackable %>
		
		<% step = activity.trackable %>
		<% project = activity.trackable.project %>
		<div class = "notification">
			<p class ="notification-image">
				<% if activity.owner.avatar.present? %>
					<%= link_to image_tag(activity.owner.avatar_url(:thumb), :class=>"img-rounded"), user_path(activity.owner) %>
				<% else %>
					<%= link_to image_tag("default_avatar.png", :class=>"img-rounded"), user_path(activity.owner) %>
				<% end %>
			</p>
			<p class="notification-text">
				<%= link_to activity.owner.username, user_path(activity.owner) if activity.owner %> <%if activity.key == "step.create" %> created <% else %> updated <% end %> <%= link_to step.name, project_steps_path(project, :step => step.id) %> in <%= link_to project.title, project_path(project) %> 
			</p>
			<p class="notification-date"><%= time_ago_in_words(activity.created_at) %> ago</p>
			<div class="clear"></div>
			<hr style="margin: 5px;">
		</div>
	<% end %>
<% end %>

app/views/collections/_collection_people.html.erb
<div class="label">Contributors (<%=@contributors.length%>)</div>
<br>
<% @contributors.each do |contributor| %>
	<p class="notification-image">
	<% if contributor.avatar.present? %>
 		<%= link_to image_tag(contributor.avatar_url(:thumb), :class=>"avatar img-rounded"), user_path(contributor), :title => contributor.username %>
    <% else %>
        <%= link_to image_tag("default_avatar.png", :class=>"avatar img-rounded"), user_path(contributor),  :title => contributor.username %>
     <% end %>
 </p>
<% end %>
<div style="clear: both;"></div>

app/views/collections/_collection_title.html.erb
<div id="collectionInfoContainer">
  
  <div id="collectionAvatar">
    <% if @authorLoggedIn %>
      <script type="text/javascript">
      $('#collectionAvatar').css('margin-bottom', '105px');
      </script>
      <%= form_for @collection, remote: true, :html => {:id => "collection_avatar_form", :multipart => true } do |f| %>
          <div id="uploadImageWrapper" title="Edit Avatar">
        <% if @collection.image.length > 0%>
              <%= image_tag(@collection.image_url(:thumb), :class=>"img-rounded") %>
              <div id="editAvatarIcon"><icon class="fa fa-pencil"></icon></div>
      <% else %>
          <%= image_tag("default_collection.png", :class=>"collectionAvatar img-rounded") %>
            <div id="editAvatarIcon"><icon class="fa fa-pencil"></icon></div>
        <% end %>
        <%= f.file_field :image %>
      </div>
      <% end %> <%# end form %>
    <% else %>
      <% if @collection.image.length > 0%>
          <%= image_tag(@collection.image_url(:thumb), :class=>"img-rounded") %>
      <% else %>
          <%= image_tag("default_collection.png", :class=>"collectionAvatar img-rounded") %>
      <% end %>
    <% end %>
  </div>

  <div class="clear"></div>

  <div id="collectionName">
    <% if @authorLoggedIn %>
    <span id="collectionNameBIP">
      <%= best_in_place @collection, :name, :type => :textarea, :value => @collection.name,  :html_attrs => {:maxlength => 30}  %>
    </span>
    <% else %>
      <%=@collection.name%>
    <% end %>
  </div>

  <div id="collectionDescription">
    <% if @collection.description.present? %>
      <% if @authorLoggedIn %>
        <span id="collectionDescriptionBIP">
          <%= best_in_place @collection, :description, :type => :textarea, :sanitize => false, :value => @collection.description, :place_holder => "Click to add a description to your collection",  :html_attrs => {:maxlength => 80} %>
        </span>
      <% else %>
        <%= @collection.description %>
      <% end %>
    <% elsif current_user == @collection.user %>
      <%= best_in_place @collection, :description, :type => :textarea, :nil => @collection.description, :sanitize => false, :value => "Click to add a description to your collection", :place_holder => "Click to add a description to your collection",  :html_attrs => {:maxlength => 80} %>
    <% end %>
  </div>

  <div id="collectionInfo">
    <%= @collection.projects.count %> <i class="fa fa-folder-open"></i> &nbsp;|&nbsp; <%= link_to @collection.user.username, user_path(@collection.user), :class=>"username" %>
    
    <div id="collectionPrivacy">
      <% if @collection.user == current_user %>
        <div class="btn-group">
             <% if @collection.public? %>
                <button type="button" class="btn btn-xs currentPrivacy"><icon class="fa fa-globe"></icon> Public</button>
                <button type="button" class="btn btn-xs dropdown-toggle" data-toggle="dropdown" style="border-top-right-radius: 4px;">
                  <span class="caret"></span>
                </button>
                <ul class="dropdown-menu" role="menu">
                  <li>
                    <%= link_to raw('<icon class="fa fa-unlock-alt"></icon> Unlisted'), update_privacy_collection_url(@collection, :privacy => "unlisted") %>
                  </li>
                  <li>
                    <%= link_to raw('<icon class="fa fa-lock"></icon> Private'), update_privacy_collection_url(@collection, :privacy => "private") %>
                  </li>
                </ul>          
          <% elsif @collection.unlisted? %>
                <button type="button" class="btn btn-xs currentPrivacy"><icon class="fa fa-unlock-alt"></icon> Unlisted</button>
                <button type="button" class="btn btn-xs dropdown-toggle" data-toggle="dropdown" style="border-top-right-radius: 4px;">
                  <span class="caret"></span>
                </button>
                <ul class="dropdown-menu" role="menu">
                  <li>
                    <%= link_to raw('<icon class="fa fa-lock"></icon> Private'), update_privacy_collection_url(@collection, :privacy => "private") %>
                  </li>
                  <% if @collection.published? %>
                    <li>
                       <%= link_to raw('<icon class="fa fa-globe"></icon> Public'), update_privacy_collection_url(@collection, :privacy => "public") %>
                    </li>
                  <% end %>
                </ul>     
          <% elsif @collection.private? %>
             <button type="button" class="btn btn-xs currentPrivacy"><icon class="fa fa-lock"></icon> Private</button>
                <button type="button" class="btn btn-xs dropdown-toggle" data-toggle="dropdown" style="border-top-right-radius: 4px;">
                  <span class="caret"></span>
                </button>
                <ul class="dropdown-menu" role="menu">
                  <li>
                    <%= link_to raw('<icon class="fa fa-unlock-alt"></icon> Unlisted'), update_privacy_collection_url(@collection, :privacy => "unlisted") %>
                  </li>
                  <% if @collection.published? %>
                    <li>
                      <%= link_to raw('<icon class="fa fa-globe"></icon> Public'), update_privacy_collection_url(@collection, :privacy => "public") %>
                    </li>
                  <% end %>
                </ul>  
          <% else %>  <%# project is not yet published %>
            <button type="button" class="btn btn-xs currentPrivacy"><icon class="fa fa-unlock-alt"></icon> Unlisted</button>
                <button type="button" class="btn btn-xs dropdown-toggle" data-toggle="dropdown" style="border-top-right-radius: 4px;">
                  <span class="caret"></span>
                </button>
                <ul class="dropdown-menu" role="menu">
                  <li>
                    <%= link_to raw('<icon class="fa fa-lock"></icon> Private'), update_privacy_collection_url(@collection, :privacy => "private") %>
                  </li>
                </ul>     
          <% end %>
      </div>
    <% else %>
      <% if @collection.public? %>
        <icon class="fa fa-globe"></icon> Public
      <% elsif @collection.private? %>
        <icon class="fa fa-lock"></icon> Private
      <% else %>
        <icon class="fa fa-unlock-alt"></icon> Unlisted
      <% end %>
    <% end %>
  </div>
</div>

<% if @authorLoggedIn %>
 <%=link_to raw('<i class="btn btn-danger fa fa-trash-o" style="height: 20px; font-size: 18px; position: absolute; top: 28px; right: 20px;"></i>'), @collection, :method=> :delete, :data=> {:confirm=>  "Are you sure you want to delete this collection?"}, :class=>"deleteCollectionButton"%>
 <% end %>


</div>

<script type="text/javascript">
  $('#collectionName').hover(function(){
    if("<%=@authorLoggedIn%>" == "true"){
      $(this).css('background', '#7a7a7a');
       }
    }, function(){
      if("<%=@authorLoggedIn%>"=="true"){
        $(this).css('background', 'none');
      }
    });

  $('#collectionDescription').hover(function(){
        if("<%=@authorLoggedIn%>" == "true"){
      $(this).css('background', '#7a7a7a');
       }
    }, function(){
      if("<%=@authorLoggedIn%>"=="true"){
        $(this).css('background', 'none');
      }
  });

  $('#collectionAvatar').hover(function(){
    if("<%=@authorLoggedIn%>"=="true"){
      $(this).addClass('editing');
      $('#editAvatarIcon').show();
    }
  }, function(){
    $(this).find('img').css('border', '3px solid rgba(97, 97, 97, 0.8)');
    $(this).removeClass('editing');
    $('#editAvatarIcon').hide();
  });


  $('#s3-image-uploader').bind("ajax:success", function(e, data){
    console.log('uploaded new avatar to s3 at url: ' + content.url);
    $('#uploadImageWrapper').find('img').attr('src', content.url);
  });

  $('#collection_image').change(function(){
    var F = this.files;

    var reader = new FileReader();
    var image  = new Image();
    reader.readAsDataURL(F[0]);  
    reader.onload = function(_file){
        image.src    = _file.target.result;              // url.createObjectURL(file);
        image.onload = function() {
            $('#collectionAvatar').find('img').attr('src', this.src);
        };
    }

    $.ajax({
          type: "POST",
          url: $('#collection_avatar_form').attr('action'), //sumbits it to the given url of the form
          data: new FormData($('#collection_avatar_form')[0]),
          processData: false,
          contentType: false,          
          dataType: "JSON" // you want a difference between normal and ajax-calls, and json is standard
      }).success(function(json){
          console.log("success", json);
    });

  });

  $('.best_in_place').keydown(function(e){
        if(e.keyCode == 13){
          e.preventDefault();
          // console.log('pressed enter key');
          return false;
        }
  });
  
</script>

app/views/collections/_project_form.html.erb
<div class="addProjectContainer">
<%= form_tag({controller: "collections", action: "add_project"}, method: "post", :class=> "form-inline add_project_form") do %>

  <%= label_tag 'project_url', 'Add project:', :class=>"project_url_label" %>
  <%= text_field_tag 'project_url', nil, :onKeyPress => 'return disableEnterKey(event)' %>

  <div class="btn btn-info addProjectButton" style="float: right;">Add</div>

<% end %>
</div>


<%# add errorModal - used to display errors if user is trying to add a project with private or unlisted privacy settings %>

<div id="errorModal" class="modal hide fade" tabindex="-1" role="dialog" aria-hidden="true">
  <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
    <h3 id="myModalLabel">Warning</h3>
  </div>
  <div class="modal-body">
  </div>
  <div class="modal-footer">
    <button class="btn" data-dismiss="modal" aria-hidden="true">Close</button>
    <button class="btn btn-primary">Add Project</button>
  </div>
</div>

<script type="text/javascript">

	$('.addProjectButton').click(function(){
		$('#errorModal .modal-body').empty();
  	  	$.ajax({
			url:"<%=check_privacy_projects_path%>",
			type:'GET',
			data: {project_url: $('#project_url').val()},
			success: function(data,status,xhr){
				// console.log('data: ' + JSON.stringify(data));
	  			if(data){
	  				var privacy = data.project_privacy;
	  				var project_name = data.project_name;

	  				console.log('privacy: ' + privacy);
	  				console.log('project_name: ' + project_name);

	  				if (privacy== "public" || privacy == "unpublished" || "<%=@collection.privacy%>" == "private" || "<%=@collection.privacy%>" == "unlisted"){
	  					// submit the form
	  					// console.log('adding public project to collection');
	  					$('form.add_project_form').submit();
	  				}else if(privacy == "unlisted"){
	  					$('#errorModal .modal-body').append('<p><i>'+project_name +'</i> is an unlisted project.   Are you sure you want to add it to this collection? </p>');
	  					// console.log('trying to add unlisted project to collection');
	  					$('#errorModal .btn-primary').show();
	  					$('#errorModal').modal('show');

	  					// detect if add project button is clicked
	  				}else if(privacy == "private"){
						// console.log('trying to add private project to collection');
						$('#errorModal .modal-body').append("<p><i>"+project_name +"</i> is a private project. Please change this collection's privacy settings to <b>private</b> before adding this project.</p>");
						$('#errorModal .btn-primary').hide();
						$('#errorModal').modal('show');
	  				}
	  			}
  		}
		});
	});

	disableEnterKey = function(e) {
	    var code = (e.keyCode ? e.keyCode : e.which);
	    if(code == 13) { //Enter keycode
	        e.preventDefault();
	        //do somethig else
	    }
	  };

	$('#errorModal .btn-primary').click(function(){
		// user confirms that they want to add an unlisted project to the collection
		$('form.add_project_form').submit();
	});

</script>

app/views/collections/edit.js.erb
$('.error_message').css('display', 'inline');

app/views/collections/embed.html.erb
<html>
	<head>
	  <title><%= ENV["APP_NAME"] %></title>
	  <%= csrf_meta_tags %>
	  <%= javascript_include_tag "application" %>
	  <%= stylesheet_link_tag "application-all", :media => "all" %>
	</head>
	<body style="width:500px">
		<div class="embedDiv">
			<div class="embedTitle">
				<%= link_to @project.title, project_path(@project) %> by <%= render :partial => "projects/author_byline", :locals => {:project => @project, :source=>"embed"} %> 
			</div>
			<% if !@project.description.blank? %>
				<div class="projectDescription">
					<p class="description">Project Description</p>
					<%= @project.description %>
				</div>
			<% end %>
			<div class="embedLink">
				<%= image_tag("build_in_progress_logo.png", :class=> "logo" )%>
				<% tagline = "Check out all of " + @project.title + " at #{ENV["APP_NAME"]}!" %>
				<p> <%= link_to tagline, project_path(@project) %> </p>
			</div>
		</div>
	</body>
	</html>

	<script>
	// remove the user's comments on the embed page
	$(document).ready(function(){
		$('.userComments').remove();
	});

	</script>