config/routes.rb
Build::Application.routes.draw do

  devise_for :admins

  if Rails.env.development?
    mount MailPreview => 'mail_view'
  end

  get "search/new"

  get "errors/not_found"

  get "errors/unacceptable"

  get "errors/internal_error"

  get "errors/unauthorized"

  resources :notifications do
    collection {post :sort}
    get :update_seen, on: :collection
  end

  resources :activity_feed do
    collection {post :sort}
  end

  devise_for :users, :controllers => {:registrations => :registrations, omniauth_callbacks: "users/omniauth_callbacks"} 

  devise_scope :user do
      post 'registrations' => 'registrations#create', :as => 'register'
      post 'sessions' => 'sessions#create', :as => 'login'
      delete 'sessions' => 'sessions#destroy', :as => 'logout'
  end

  get "home/index"
  get "about", to: "home#about"
  get "help", to: "home#help"
  get "documentation_tips", to: "home#documentation_tips"
  get "news", to: "home#news"
  get "mobile", to: "home#mobile"
  get "mobile/request", to: "home#mobile_request"
  get "privacy_policy", to: "home#privacy_policy"
  get "dashboard", to: "home#dashboard"

  match 'contact' => 'contact#new', :as=> 'contact', :via => :get
  match 'contact' => 'contact#create', :as=> 'contact', :via=>:post
  match 'announcements/:id/hide', to: 'home#hide_announcement', as: 'hide_announcement'
  match 'search', to: 'application#search', as: :search

  resources :users, :id => /[A-Za-z0-9\-\_\.\+]+?/ , :format => /json|csv|xml|yaml/ do
     match 'users/:id' => 'users#username'
     get 'validate_username', on: :collection
     get 'validate_email', on: :collection
     get :search, on: :collection
     get 'edit_profile', on: :member
     get :projects, on: :member
     get :favorites, on: :member
     get :collections, on: :member
     get :touch, on: :collection
     member do
      get :follow
      get :unfollow
      get :following
      get :followers
     end
  end

  resources :collections do
    post :add_project, on: :member
    get :projects, on: :member
    get :challenges, on: :collection
    get :search, on: :collection
    get :update_privacy, on: :member
  end

  resources :collectifies do
  end

  resources :categories do
  end

  resources :projects do
     collection {post :sort}
     get :builds, on: :collection
     get :built, on: :collection
     get :featured, on: :collection
     get :search, on: :collection
     get :editTitle, on: :collection
     post :categorize, on: :member
     put :favorite, on: :member
     put :remix, on: :member
     get :embed, on: :member
     get :gallery, on: :member
     get :imageView, on: :member
     get :blog, on: :member
     get :export, on: :member
     get :export_txt, on: :member
     get :update_privacy, on: :member
     get :find_users, on: :collection
     get :add_users, on: :collection
     get :remove_user, on: :collection
     get :check_privacy, on: :collection
     get :log, on: :member
     get :timemachine, on: :member
    resources :steps do
        collection {post :sort}
        resources :comments, :only => [:create, :destroy]
        get :create_branch, on: :collection
        get :reset_started_editing, on: :member
        get :update_ancestry, on: :collection
        get :edit_redirect, on: :collection
        get :get_position, on: :collection
        get :show_redirect, on: :collection
        get :update_new_image, on: :member
        get :mobile, on: :collection
      end
      match "steps/:id" => "steps#number", :as => :number
  end

  resources :images do
     collection {post :sort}
     get :find_image_id, on: :collection
     get :rotate, on: :member
     get :export, on: :member
  end

  resources :charts do
    get :users, on: :collection
    get :users_by_month, on: :collection
    get :steps, on: :collection
    get :steps_by_month, on: :collection
    get :comments, on: :collection
    get :comments_by_month, on: :collection
  end

  get "videos/embed_url" => "videos#embed_url", :as => :video_embed_url
  
  resources :videos do
    post :create_mobile, on: :collection
  end

  resources :sounds do
  end
      
  resources :design_files do
  end

  root :to => 'home#index'

  post "versions/:id/revert" => "versions#revert", :as => "revert_version"

  %w( 404 422 500 ).each do |code|
    get code, :to => "errors#show", :code => code
  end

end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_filter :authenticate_user!, except: [:index, :show, :embed, :builds, :built, :featured, :arts_and_crafts, :clothing, :cooking, :electronics, :mechanical, :other, :search, :imageView, :gallery, :blog, :timemachine] 

  # GET /projects
  # GET /projects.json
  def index
    if !params[:category].blank?
      @projects = Category.where(:name => params[:category]).first.projects.public_projects.order('updated_at DESC').page(params[:projects_page]).per_page(9).includes(:steps, :images)
    else
      @projects = Project.public_projects.order("updated_at DESC").page(params[:projects_page]).per_page(12).includes(:steps, :images)
    end
    respond_to do |format|
      format.html # index.html.erb
      format.js
      format.json { render :json => @projects }
    end
  end

  # GET /projects/featured - projects that have been featured
  def featured
    if !params[:category].blank?
      @projects = Category.where(:name => params[:category]).first.projects.public_projects.where(:featured=>true).order('updated_at DESC').page(params[:projects_page]).per_page(9)
    else
      @projects = Project.public_projects.where(:featured=>true).order("updated_at DESC").page(params[:projects_page]).per_page(9)
    end
    render :template => "projects/index"
  end

  # GET /projects/builds - projects that are still in progress
  def builds
    if !params[:category].blank?
      @projects = Category.where(:name => params[:category]).first.projects.public_projects.where(:built=>false).order('updated_at DESC').page(params[:projects_page]).per_page(9)
    else
      @projects = Project.public_projects.where(:built=> false).order("updated_at DESC").page(params[:projects_page]).per_page(9)
    end
    render :template =>"projects/index"
  end

  # GET /projects/built - projects that have been built
  def built
    if !params[:category].blank?
      @projects = Category.where(:name => params[:category]).first.projects.public_projects.where(:built=>true).order('updated_at DESC').page(params[:projects_page]).per_page(9)
    else
      @projects = Project.public_projects.where(:built=> true).order("updated_at DESC").page(params[:projects_page]).per_page(9)
    end
    render :template =>"projects/index"
  end

  # GET /projects/1
  # GET /projects/1.json
  def show
    begin
      @project = Project.find_by_id(params[:id])
      respond_to do |format|
        format.html {redirect_to project_steps_path(@project)}
      end
    rescue
      respond_to do |format|
        format.html {redirect_to url_for(:controller => "errors", :action => "show", :code => "404")}
      end
    end
  end

  # GET /projects/new
  # GET /projects/new.json
  def new
    @project = Project.new
    @project.description = nil

    respond_to do |format|
      format.html { create }
      format.json { create }
    end
  end

  # GET /projects/1/edit
  def edit
    @project = Project.find(params[:id])
    authorize! :edit, @project
  end

  # POST /projects
  # POST /projects.json
  def create
    @project = Project.new(params[:project])

    # set some default values
    numUntitled = current_user.projects.where("title like ?", "%Untitled%").count
    @project.title = "Untitled-"+ (numUntitled+1).to_s()
    @project.built = false
    @project.users << current_user

    respond_to do |format|
      if @project.save
        # if user is from village, push project to village
        format.html { redirect_to @project }
        format.json { render :json => @project, :status => :created, :location => @project }
      else
        format.html { render :action => "new" }
        format.json { render :json => @project.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /projects/1
  # PUT /projects/1.json
  def update
    @project = Project.find(params[:id])
    authorize! :update, @project
    @collections = @project.collections

    @collections.each do |collection|
      collection.touch
    end

    respond_to do |format|
      if @project.update_attributes(params[:project])
        
        if @project.privacy.blank?
            @project.set_published(current_user.id, @project.id, nil)
        elsif @project.title.downcase.include? "untitled"
            @project.set_published(current_user.id, @project.id, nil)
        end

        if @project.public? && @project.village_id.blank? && current_user.from_village? && !access_token.blank?
          Rails.logger.debug("creating village project")
          create_village_project(@project.id)
        elsif @project.published? && @project.village_id.present? && current_user.from_village? && access_token.present?
          Rails.logger.debug("updating village project")
          update_village_project(@project.id)          
        end
        format.html { redirect_to @project, :notice => 'Project was successfully updated.' }
        format.js
        format.json { head :no_content }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @project.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    @project = Project.find(params[:id])
    authorize! :destroy, @project

    # delete activities having to do with the project
    PublicActivity::Activity.where("trackable_type = ? AND trackable_id = ?", "Project", @project.id).destroy_all
    @project.questions.each do |question|
      PublicActivity::Activity.where("trackable_type = ? AND trackable_id = ?", "Question", question.id).destroy_all
    end

    # delete all favorites
    favorite_entry = FavoriteProject.where(:user_id=>current_user.id).where(:project_id => @project.id).first
    if favorite_entry
      PublicActivity::Activity.where("trackable_type = ? AND trackable_id = ?", "FavoriteProject", favorite_entry.id).destroy_all
    end

    # delete all collectifies
    Collectify.where(:project_id=>@project.id).each do |collectify|
       collectify.destroy
    end

    @project.steps.each do |step|
      PublicActivity::Activity.where(:trackable_id => step.id).destroy_all
    end

    if !@project.village_id.blank?
      # delete project on the village
      destroy_village_project(@project.village_id)
    end

    # if project has descendants, set their remix_ancestry to nil or project's ancestor
    @project.descendants.each do |descendant|
      if @project.remix_ancestry == nil
        descendant.update_column("remix_ancestry", nil)
      else
        descendant.update_column("remix_ancestry", @project.remix_ancestry)
      end
    end

    # remove the log for project
    s3 = AWS::S3.new(:access_key_id => ENV['AWS_ACCESS_KEY_ID'], :secret_access_key => ENV['AWS_ACCESS_KEY'])
    key = "logs/" + @project.id.to_s + ".json"
    s3.buckets[ENV['AWS_BUCKET']].objects.with_prefix(key).delete_all

    @project.destroy

    respond_to do |format|
      format.html { redirect_to user_path(current_user.username) }
      format.json { head :no_content }
    end
  end

  # editTitle /project/1/editTitle
  def editTitle
    @projectID = params[:projectID]
    respond_to do |format|
      logger.debug("edit Title")
      format.js
    end
  end

  # PUT /projects/1/embed
  # Embed code for displaying Build-in-Progress project on another site
  def embed
    @project = Project.find(params[:id])
    @steps = @project.steps.order("position")
    @ancestry = @steps.pluck(:ancestry) # array of ancestry ids for all steps
    
    respond_to do |format|
      format.html {render :layout=> false}
      format.js
    end
  end

  # GET /project/1/imageView
  # imageView view of project
  def imageView
    @project = Project.find(params[:id])
    redirect_to gallery_project_url(@project)
  end

  # GET /projects/1/galery
  # gallery view of project
  def gallery
    @project = Project.find(params[:id])
  end

  # GET /projects/1/blog
  # blog view of project
  def blog
    @project = Project.find(params[:id])
  end

  # GET /projects/1/export
  # Expot a zip of a project page
  def export
    @project = Project.find(params[:id])
    @project.export
    if current_user && @project.users.include?(current_user)
      current_user.touch
    end
    send_file "#{Rails.root}/tmp/zips/#{@project.id}-#{@project.title.delete(' ')}.zip"
  end

  # GET /project/1/export_txt
  # Export a txt file of a project page
  def export_txt
    @project = Project.find(params[:id])
    @project.export_txt
    send_file "#{Rails.root}/tmp/txt/#{@project.id}.txt"
  end

  # Add and remove favorite projects for current user
  def favorite
    type=params[:type]
    @project = Project.find(params[:id])

    if type=="favorite"
      if current_user.favorites.include?(@project) == false
        current_user.favorites << @project
      end
      @project.users.each do |user|
        @activity = @project.favorite_projects.last.create_activity :create, owner: current_user, recipient: user, primary: true
        # create email notification
        if user.settings(:email).favorited == true
          NotificationMailer.delay.notification_message(@activity, user)
        end

      end
    elsif type=="unfavorite"
      favorite_entry = FavoriteProject.where(:user_id=>current_user.id).where(:project_id => @project.id).first
      PublicActivity::Activity.where("trackable_type = ? AND trackable_id = ?", "FavoriteProject", favorite_entry.id).destroy_all

      current_user.favorites.delete(@project)
    end
      redirect_to :back
  end

  # Create remix
  def remix
    @project = Project.find(params[:id])
    @remix_project = @project.remix(current_user)

    respond_to do |format|    
        format.html {
          redirect_to @remix_project 
        }   
    end
  end

  # find users to add to a project using the EditProjectAuthors Modal Form
  # params[:input] - string user has inputted into the search field
  # params[:project_id] - the id of the project being edited
  def find_users

app/helpers/projects_helper.rb
module ProjectsHelper
	
end

app/views/public_activity/project/_author_add.html.erb
<% # Add User as Author to Project Public Activity %>

<% source = params[:source] %>
<% project = activity.trackable %>

<% if project %>
	<% if source == "navbar" %>
		<%= link_to project_path(project, :notification_id=>activity.id) do %>
			<icon class="fa fa-plus"></icon>
			<p class="notification-image">
				<%= render :partial=>"images/navbar_image", :locals=> {:activity => activity} %>
			</p>
			<p class="notification-text">
				<span class="notification-bold"><%= activity.owner.username %></span> added <% if activity.recipient == current_user %>you<% else %><span class="notification-bold"><%= link_to activity.recipient.username, user_path(activity.recipient) %></span><% end %> as an collaborator on <span class="notification-bold"><%= activity.trackable.title %> </span>
			</p>
			<br>
			<p class="notification-date" style="display:inline-block"><%= time_ago_in_words(activity.created_at) %> ago</p>
		<% end %>
	<% else %>
		<icon class="fa fa-plus"></icon>
		<p class ="notification-image">
			<% if activity.owner.avatar.present? %>
				<%= link_to image_tag(activity.owner.avatar_url(:thumb), :class=>"img-rounded"), user_path(activity.owner) %>
			<% else %>
				<%= link_to image_tag("default_avatar.png", :class=>"img-rounded"), user_path(activity.owner) %>
			<% end %>
		</p>
		<p class="notification-heading">
			<%= link_to activity.owner.username, user_path(activity.owner) %> added <% if activity.recipient == current_user %>you<% else %><%= link_to activity.recipient.username, user_path(activity.recipient) %><%end%> as a collaborator on <%= link_to activity.trackable.title, project_path(activity.trackable, :notification_id=>activity.id) %> 	
		</p>
		<span class="notification-date"><%= time_ago_in_words(activity.created_at) %> ago</span>
	<% end %>
<% end %>

app/views/public_activity/project/_create.html.erb
<% # Create Project Public Activity %>

<% source = params[:source] %>
<% project = activity.trackable %>

<% if project %>
	<% remix = !activity.trackable.remix_ancestry.blank? %> <%# boolean - whether or not the project is a remix %>

	<% if project.is_remix? %>
		<% original_project = Project.find_by_id(activity.trackable.root) %>
	<% else %>
		<% original_project = false %>
	<% end %>

	<% if original_project %>
		<% if source == "navbar" %>
			<%= link_to project_steps_path(project, :notification_id => activity.id) do %>
				<icon class="fa fa-code-fork"></icon>
				<p class="notification-image">
					<%= render :partial=>"images/navbar_image", :locals=> {:activity => activity} %>
				</p>
				<p class="notification-text">
					<span class="notification-bold"><%= activity.owner.username if activity.owner %></span> remixed <span class="notification-bold"><%= original_project.title if original_project %> <%= "[Deleted Project]" if !original_project %></span>
				</p>
				<br>
				<p class="notification-date" style="display:inline-block"><%= time_ago_in_words(activity.created_at) %> ago</p>
			<% end %>
		<% else %>
			<icon class="fa fa-code-fork"></icon>
			<p class ="notification-image">
				<% if activity.owner.avatar.present? %>
					<%= link_to image_tag(activity.owner.avatar_url(:thumb), :class=>"img-polaroid"), user_path(activity.owner) %>
				<% else %>
					<%= link_to image_tag("default_avatar.png", :class=>"img-polaroid"), user_path(activity.owner) %>
				<% end %>
			</p>
			<p class="notification-heading">
				<%= link_to activity.owner.username, user_path(activity.owner) if activity.owner %> remixed <%= link_to original_project.title, project_steps_path(project, :notification_id => activity.id) if original_project %> <%= "[Deleted Project]" if !original_project %>	</span>
			</p>
			<span class="notification-date"><%= time_ago_in_words(activity.created_at) %> ago</span>
		<% end %>
	<% end %>
<% end %>

app/views/public_activity/project/_feature.html.erb
<% # Create Project Notification %>

<% source = params[:source] %>
<% project = activity.trackable %>
<% if project %>
	<% if source == "navbar" %>
		<%= link_to project_path(project, :notification_id => activity.id) do %>
			<icon class="fa fa-thumb-tack"></icon>
			<p class="notification-image">
				<%= render :partial=>"images/navbar_image", :locals=> {:activity => activity} %>
			</p>
			<p class="notification-text">
				<span class="notification-bold"><%= project.title %></span> has been featured!
			</p>
			<br>
			<p class="notification-date" style="display:inline-block"><%= time_ago_in_words(activity.created_at) %> ago</p>
		<% end %>
	<% else %>
		<icon class="fa fa-thumb-tack"></icon>
		<p class ="notification-image">
			<%= link_to image_tag(project.default_image.image_path_url(:square_thumb), :class=>"img-rounded"), home_index_path %>
		</p>
		<p class="notification-heading">
			<%= link_to project.title, project_path(project) %></span> has been featured!
		</p>
		<span class="notification-date"><%= time_ago_in_words(activity.created_at) %> ago</span>
	<% end %>
<% end %>

app/views/public_activity/project/_feature_public.html.erb
<% # Create Project Notification %>

<% source = params[:source] %>
<% project = activity.trackable %>
<% if project %>
	<% if source == "navbar" %>
		<%= link_to project_path(project) do %>
			<icon class="fa fa-thumb-tack"></icon>
			<p class="notification-image">
				<%= render :partial=>"images/navbar_image", :locals=> {:activity => activity} %>
			</p>
			<p class="notification-text">
				<span class="notification-bold"><%= project.title %></span> has been featured
			</p>
			<br>
			<p class="notification-date" style="display:inline-block"><%= time_ago_in_words(activity.created_at) %> ago</p>
		<% end %>
	<% else %>
		<icon class="fa fa-thumb-tack"></icon>
		<p class ="notification-image">
			<%= link_to image_tag(project.default_image.image_path_url(:square_thumb), :class=>"img-rounded"), home_index_path %>
		</p>
		<p class="notification-heading">
			<%= link_to project.title, project_path(project) %> by <%= render :partial => "projects/author_byline", :locals => {:project => project, :source => "home" } %> has been featured!</span>
		</p>
		<span class="notification-date"><%= time_ago_in_words(activity.created_at) %> ago</span>
	<% end %>
<% end %>

app/views/public_activity/project/_new.html.erb
<% # Create Project Notification %>

<% source = params[:source] %>
<% project = activity.trackable %>
<% if project %>
	<% if source == "navbar" %>
		<%= link_to project_path(project) do %>
			<icon class="fa fa-plus"></icon>
			<p class="notification-image">
				<%= render :partial=>"images/navbar_image", :locals=> {:activity => activity} %>
			</p>
			<p class="notification-text">
				<span class="notification-bold"><%= activity.owner.username if activity.owner %></span> created a new project: <span class="notification-bold"><%= project.title %></span>
			</p>
			<br>
			<p class="notification-date" style="display:inline-block"><%= time_ago_in_words(activity.created_at) %> ago</p>
		<% end %>
	<% else %>
		<icon class="fa fa-plus"></icon>
		<p class ="notification-image">
			<% if activity.owner.avatar.present? %>
				<%= link_to image_tag(activity.owner.avatar_url(:thumb), :class=>"img-rounded"), user_path(activity.owner) %>
			<% else %>
				<%= link_to image_tag("default_avatar.png", :class=>"img-rounded"), user_path(activity.owner) %>
			<% end %>
		</p>
		<p class="notification-heading">
			<%= link_to activity.owner.username, user_path(activity.owner) if activity.owner %> created a new project: <%= link_to project.title, project_path(project) %> 	
		</p>
		<span class="notification-date"><%= time_ago_in_words(activity.created_at) %> ago</span>
	<% end %>
<% end %>