config/routes.rb
Build::Application.routes.draw do

  devise_for :admins

  if Rails.env.development?
    mount MailPreview => 'mail_view'
  end

  get "search/new"

  get "errors/not_found"

  get "errors/unacceptable"

  get "errors/internal_error"

  get "errors/unauthorized"

  resources :notifications do
    collection {post :sort}
    get :update_seen, on: :collection
  end

  resources :activity_feed do
    collection {post :sort}
  end

  devise_for :users, :controllers => {:registrations => :registrations, omniauth_callbacks: "users/omniauth_callbacks"} 

  devise_scope :user do
      post 'registrations' => 'registrations#create', :as => 'register'
      post 'sessions' => 'sessions#create', :as => 'login'
      delete 'sessions' => 'sessions#destroy', :as => 'logout'
  end

  get "home/index"
  get "about", to: "home#about"
  get "help", to: "home#help"
  get "documentation_tips", to: "home#documentation_tips"
  get "news", to: "home#news"
  get "mobile", to: "home#mobile"
  get "mobile/request", to: "home#mobile_request"
  get "privacy_policy", to: "home#privacy_policy"
  get "dashboard", to: "home#dashboard"

  match 'contact' => 'contact#new', :as=> 'contact', :via => :get
  match 'contact' => 'contact#create', :as=> 'contact', :via=>:post
  match 'announcements/:id/hide', to: 'home#hide_announcement', as: 'hide_announcement'
  match 'search', to: 'application#search', as: :search

  resources :users, :id => /[A-Za-z0-9\-\_\.\+]+?/ , :format => /json|csv|xml|yaml/ do
     match 'users/:id' => 'users#username'
     get 'validate_username', on: :collection
     get 'validate_email', on: :collection
     get :search, on: :collection
     get 'edit_profile', on: :member
     get :projects, on: :member
     get :favorites, on: :member
     get :collections, on: :member
     get :touch, on: :collection
     member do
      get :follow
      get :unfollow
      get :following
      get :followers
     end
  end

  resources :collections do
    post :add_project, on: :member
    get :projects, on: :member
    get :challenges, on: :collection
    get :search, on: :collection
    get :update_privacy, on: :member
  end

  resources :collectifies do
  end

  resources :categories do
  end

  resources :projects do
     collection {post :sort}
     get :builds, on: :collection
     get :built, on: :collection
     get :featured, on: :collection
     get :search, on: :collection
     get :editTitle, on: :collection
     post :categorize, on: :member
     put :favorite, on: :member
     put :remix, on: :member
     get :embed, on: :member
     get :gallery, on: :member
     get :imageView, on: :member
     get :blog, on: :member
     get :export, on: :member
     get :export_txt, on: :member
     get :update_privacy, on: :member
     get :find_users, on: :collection
     get :add_users, on: :collection
     get :remove_user, on: :collection
     get :check_privacy, on: :collection
     get :log, on: :member
     get :timemachine, on: :member
    resources :steps do
        collection {post :sort}
        resources :comments, :only => [:create, :destroy]
        get :create_branch, on: :collection
        get :reset_started_editing, on: :member
        get :update_ancestry, on: :collection
        get :edit_redirect, on: :collection
        get :get_position, on: :collection
        get :show_redirect, on: :collection
        get :update_new_image, on: :member
        get :mobile, on: :collection
      end
      match "steps/:id" => "steps#number", :as => :number
  end

  resources :images do
     collection {post :sort}
     get :find_image_id, on: :collection
     get :rotate, on: :member
     get :export, on: :member
  end

  resources :charts do
    get :users, on: :collection
    get :users_by_month, on: :collection
    get :steps, on: :collection
    get :steps_by_month, on: :collection
    get :comments, on: :collection
    get :comments_by_month, on: :collection
  end

  get "videos/embed_url" => "videos#embed_url", :as => :video_embed_url
  
  resources :videos do
    post :create_mobile, on: :collection
  end

  resources :sounds do
  end
      
  resources :design_files do
  end

  root :to => 'home#index'

  post "versions/:id/revert" => "versions#revert", :as => "revert_version"

  %w( 404 422 500 ).each do |code|
    get code, :to => "errors#show", :code => code
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index

  	if current_user
  		@activities = current_user.followers_activity.where("created_at > ? ", 2.weeks.ago).public_activities.uniq_by(&:trackable_id).first(10)
  	end

    @community_activity_array = Array.new

    questions = Question.where("created_at >?", 1.month.ago).featured.unanswered.limit(10).order("RANDOM()")
    # add to community activity array questions with the format ["question", question_description, project_title, project_id, step_id]
    questions.each_with_index do |question, index|
      if question.step.project.public?
        question_holder = Array.new
        question_holder = ["question", question.description, question.step.project.title, question.step.project.id, question.step.id]
        @community_activity_array << question_holder
      end
    end

    comments = Comment.featured.order('created_at DESC').first(10).shuffle.select {|comment| comment.body.length > 40}
    # add to the community activity array comments with the format ["comment", comment_description, project_title, project_id, step_id]
    comments.each do |comment|
      if comment.commentable.project.public?
        comment_holder = Array.new
        comment_holder = ["comment", comment.body, comment.commentable.project.title, comment.commentable.project.id, comment.commentable.id]
        @community_activity_array << comment_holder
      end
    end

    Rails.logger.debug("@community_activity : #{@community_activity}")

  	@latestProjects = Project.public_projects.order("updated_at DESC").limit(5)
  	@featuredProjects = Project.featured.public_projects.order("featured_on_date DESC").limit(4)
    # @comments = Comment.last(20).where("length(body) > 20").limit(5)

    @newsItems = News.order("created_at DESC").limit(2)

    if @newsItems.length > 0 && @newsItems.first.created_at > 1.week.ago
      @latestNews = @newsItems.first
    end

  end

  def hide_announcement
  	cookies.permanent.signed[:hidden_announcement_id] = params[:id]
  	respond_to do |format|
  		format.html {redirect_to :back}
  		format.js
  	end
  end

  def mobile_request_create
     @message = Message.new(params[:message])
     if @message.valid?
        MobileMailer.new_message(@message).deliver
        redirect_to(mobile_path, :notice => "Your request has been sent!")
      else
         flash.now.alert = "Please fill all fields."
         render :mobile_android
      end
  end

  # dashboard page
  def dashboard
    if current_user && current_user.admin?
      
      respond_to do |format|
        format.html
        format.csv {send_data Step.description_to_csv}
      end
    else 
      redirect_to url_for(:controller => "errors", :action => "show", :code => "401")
    end
  end

end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_short_news.html.erb
<div class="newsContainer">
	<% @newsItems.each do |news_item| %>
		<% if news_item.news_type == "website" %>
			<div class="website_news home_news_item">
				<icon class="fa fa-desktop news_icon" style="font-size: 20px; font-weight: bold; margin-top: 8px; margin-right: 18px;"></icon>
		<% elsif news_item.news_type == "mobile" %>
			<div class="mobile_news home_news_item">
				<icon class ="fa fa-mobile news_icon" style="font-size: 40px;"></icon>
		<% end %>
			<p class="news_headline"><%= link_to news_item.title, news_path(:anchor => news_item.id) %></p>
			<% if news_item.description %>
				<p class="news_description"><%= news_item.description.html_safe %></p>
			<% end %>
			<div class="clear"></div>
			</div>
	<% end %>
</div>

app/views/home/dashboard.html.erb
<% title "Dashboard | #{ENV["APP_NAME"]}" %>
<div class="fullRow" style="margin-top:50px;width:940px" id="dashboard">
	<div class="centeredContainer" style="padding: 30px">
		<h1>Dashboard <%=Time.now.strftime("%B %d, %Y %H:%M") %></h1>
		<hr>
		<h4>Registration</h4>
			<% new_users = User.where("created_at >?", 24.hours.ago).where("confirmed_at IS NOT NULL") %>
			<p><b><%=User.where("sign_in_count > ?", 0).count%></b> confirmed users</p>
			<p><b><%= new_users.count %></b> users created today</p>

			<% if new_users.count > 0 %>
				<div class="section">
									
					<div class="column"><b>USERNAME</b></div>
					<div class="column" style="width: 300px;"><b>EMAIL</b></div>
					<div class="column"><b>PROVIDER</b></div>
					<div style="clear: both;"></div>

					<% new_users.each do |user| %>
						<div class="column"><%= link_to user.username, user_path(user) %> </div>
						<div class="column" style="width: 300px;"><%= user.email %></div>
						<div class="column"><% if user.provider.present? %><%= user.provider %><% else %>none<%end%></div>
						<div style="clear: both;"></div>
					<% end %>
				</div>
			<% end %>
		<hr><!-- end registration section -->

		<h4>Projects</h4>
			<p><b><%=Project.all.count%></b> total projects | <b><%=Project.public_projects.count + Project.private_projects.count + Project.unlisted_projects.count %></b> public, private, or unlisted projects| <b><%=Project.public_projects.count %></b>  public | <b><%=Project.private_projects.count %></b> private | <b><%=Project.unlisted_projects.count %></b> unlisted</p>

			<% new_projects = Project.where("created_at >?", 24.hours.ago) %>
			<p><b><%= new_projects.count %></b> projects created today</p>
			
			<% if new_projects.count > 0 %>
				<div class="section">
					<div class="column" style="width: 40%;"><b>USERS</b></div>
					<div class="column" style="width: 40%;"><b>PROJECT</b></div>
					<div style="clear: both;"></div>

				<% new_projects.each do |project| %>
					<div class="column" style="width: 40%;"><%= project.users.order("username ASC").map { |u| "<a href='#{user_path(u)}'>#{u.username}</a>" }.to_sentence.html_safe %></div>
					<div class="column" style="width: 40%;"><%=link_to project.title, project_path(project) %></div>
					<div style="clear: both;"></div>
				<% end %>

				</div>
			<% end %>

			<% updated_projects = Project.where("updated_at > ?", 24.hours.ago).where("created_at <?", 24.hours.ago) %>
			<p><b><%= updated_projects.count %></b> projects updated today</p>

			<% if updated_projects.count > 0 %>
				<div class="section">
					<div class="column" style="width: 40%;"><b>USERS</b></div>
					<div class="column" style="width: 40%;"><b>PROJECT</b></div>
					<div style="clear: both;"></div>

				<% updated_projects.each do |project| %>
					<div class="column" style="width: 40%;"><%= project.users.order("username ASC").map { |u| "<a href='#{user_path(u)}'>#{u.username}</a>" }.to_sentence.html_safe %></div>
					<div class="column" style="width: 40%;"><%=link_to project.title, project_path(project) %></div>
					<div style="clear: both;"></div>
				<% end %>

				</div>
			<% end %>


		<hr><!-- end projects section -->

		<h4>Comments</h4>
			<% new_comments = Comment.where("created_at >?", 24.hours.ago) %>
			<p><b><%=new_comments.count %></b> comments created today </p>

			<% if new_comments.count > 0 %>
				<div class="section">
						<div class="column"><b>USER</b></div>
						<div class="column" style="width:500px;"><b>BODY</b></div>
						<div style="clear: both;"></div>

					<% new_comments.each do |comment| %>
						<%=link_to user_path(comment.user) do %>
							<div class="column"><%=comment.user.username%></div>
						<% end %>
						<div class="column" style="width: 500px;"><%= link_to comment.body, project_steps_path(comment.commentable.project, :comment_id => comment.id, :step => comment.commentable.id)%></div>
						<div style="clear: both;"></div>
					<% end %>
				</div>
			<% end %>
		<hr><!-- end comment section -->


		<h4>Collections</h4>
			<p><b><%=Collection.all.count%></b> total collections | <b><%=Collection.public_collections.count %></b>  public | <b><%=Collection.private_collections.count %></b> private | <b><%=Collection.unlisted_collections.count %></b> unlisted</p>

			<% new_collections = Collection.where("created_at >?", 24.hours.ago) %>
			<p><b><%= new_collections.count %></b> collections created today</p>
			<% if new_collections.count > 0 %>
				<div class="section">
					<div class="column" style="width: 40%;"><b>USER</b></div>
					<div class="column" style="width: 40%;"><b>COLLECTION</b></div>
					<div style="clear: both;"></div>

				<% new_collections.each do |collection| %>
					<div class="column" style="width: 40%;"><%= link_to collection.user.username, collection_path(collection)%></div>
					<div class="column" style="width: 40%;"><%=link_to collection.name, collection_path(collection) %></div>
					<div style="clear: both;"></div>
				<% end %>

				</div>
			<% end %>

			<% updated_collections = Collection.where("created_at <?", 24.hours.ago).where("updated_at >?", 24.hours.ago) %>
			<p><b><%= updated_collections.count %></b> collections updated today</p>
			<% if updated_collections.count > 0 %>
				<div class="section">
					<div class="column" style="width: 40%;"><b>USER</b></div>
					<div class="column" style="width: 40%;"><b>COLLECTION</b></div>
					<div style="clear: both;"></div>

				<% updated_collections.each do |collection| %>
					<div class="column" style="width: 40%;"><%= link_to collection.user.username, collection_path(collection)%></div>
					<div class="column" style="width: 40%;"><%=link_to collection.name, collection_path(collection) %></div>
					<div style="clear: both;"></div>
				<% end %>

				</div>
			<% end %>

		<hr><!-- end projects section -->

	<div class="charts">
		<h4>User registrations - Cumulative (<%=User.where("sign_in_count>?", 0).count%>)</h4>
			<%= line_chart users_charts_path %>
		<h4>User registrations - By month</h4>
			<%= line_chart users_by_month_charts_path %>
			<% users_count_array = User.group_by_month(:created_at).count.values.last(12) %>
		<p>Average user registrations per month in last year: <%= (users_count_array.sum / users_count_array.size.to_f).round(1) %></p>
		<hr>

		<h4>Projects - Cumulative (<%=Project.all.count%>)</h4>
			<% public_sum = 0 %>
			<% public_data = Project.public_projects.group_by_month(:created_at).count.map { |x,y| { x => (public_sum+=y)} }.reduce({}, :merge) %>

			<% private_sum = 0 %>
			<% private_data = Project.private_projects.group_by_month(:created_at).count.map { |x,y| { x => (private_sum+=y)} }.reduce({}, :merge) %>

			<% unlisted_sum = 0 %>
			<% unlisted_data = Project.unlisted_projects.group_by_month(:created_at).count.map { |x,y| { x => (unlisted_sum+=y)} }.reduce({}, :merge) %>

			<% unpublished_sum = 0 %>
			<% unpublished_data = Project.where(:privacy => nil).group_by_month(:created_at).count.map { |x,y| { x => (unpublished_sum+=y)} }.reduce({}, :merge) %>

			<%= line_chart [
				{name: "Public (" + Project.public_projects.count.to_s + ")", data: public_data},
				{name: "Private (" + Project.private_projects.count.to_s + ")", data: private_data},
				{name: "Unlisted (" + Project.unlisted_projects.count.to_s + ")", data: unlisted_data},
				{name: "Unpublished (" + Project.where(:privacy => nil).count.to_s + ")", data: unpublished_data}
			] %>

			<h4>Projects - By Month </h4>
			<% public_sum = 0 %>
			<% public_data = Project.public_projects.group_by_month(:created_at).count %>

			<% private_sum = 0 %>
			<% private_data = Project.private_projects.group_by_month(:created_at).count %>

			<% unlisted_sum = 0 %>
			<% unlisted_data = Project.unlisted_projects.group_by_month(:created_at).count %>

			<% unpublished_sum = 0 %>
			<% unpublished_data = Project.where(:privacy => nil).group_by_month(:created_at).count %>

			<%= line_chart [
				{name: "Public (" + Project.public_projects.count.to_s + ")", data: public_data},
				{name: "Private (" + Project.private_projects.count.to_s + ")", data: private_data},
				{name: "Unlisted (" + Project.unlisted_projects.count.to_s + ")", data: unlisted_data},
				{name: "Unpublished (" + Project.where(:privacy => nil).count.to_s + ")", data: unpublished_data}
			] %>

			<% projects_count_array = Project.public_projects.group_by_month(:created_at).count.values.last(12) %>
		<p>Average public projects per month in last year: <%= (projects_count_array.sum / projects_count_array.size.to_f).round(1) %></p>

			<hr>

		<h4>Steps - Cumulative (<%= Step.all.count %>)</h4>
			<%= line_chart steps_charts_path %>

		<h4>Steps - By Month </h4>
			<%= line_chart steps_by_month_charts_path %>
			<% steps_count_array = Step.group_by_month(:created_at).count.values.last(12) %>
		<p>Average steps per month in last year: <%= (steps_count_array.sum / steps_count_array.size.to_f).round(1) %></p>
		<hr>

		<h4>Comments - Cumulative (<%= Comment.all.count %>)</h4>
			<%= line_chart comments_charts_path %>

		<h4>Comments - By Month</h4>
			<%= line_chart comments_by_month_charts_path %>
			<% comments_count_array = Comment.group_by_month(:created_at).count.values.last(12) %>
		<p>Average comments per month in last year: <%= (comments_count_array.sum / comments_count_array.size.to_f).round(1) %></p>
		<hr>
		
	</div>
	
	</div><!-- end centeredContainer -->

</div><!-- end fullRow -->

app/views/home/hide_announcement.js.erb
$('.news_announcement').fadeOut();

app/views/home/index.html.erb
<% title ENV["APP_NAME"] %>

<div class="fullRow home" style="width:940px;">

    <div class="hero-unit">
        <h1><%= ENV["APP_NAME"] %></h1>
        <br>
        <div style="margin-top: 25px;">
            <%= link_to 'Create a Project', new_project_path, :class=> "btn btn-info btn-large"%> 
        </div>
    </div>
    
    <% # update to collection_path(@challenge) %>

    <% if @latestNews && (@latestNews.id != cookies.signed[:hidden_announcement_id].to_i) %>
        <div class="news_announcement homeSection">
            <div class= "announcementContent">
                <span class="announcementTitle">
                    <icon class="fa fa-bullhorn"></icon> <span class="news_title"><%= link_to @latestNews.title, news_path %> </span>
                </span>
                <% if @latestNews.description %>
                    <span style="margin-left: 10px;" class="announcementDescription"><%= @latestNews.description.html_safe %></span> 
                <% end %>
            </div>
            <div class="announcement_links">
                <%= link_to "Learn More", news_path, :class=>"announcement_link" %>  
                <% if user_signed_in? %> 
                  <%= link_to "Hide", hide_announcement_path(@latestNews.id), :class=>"announcement_link", remote: true %> </p>
                <% end %>
            </div>
   
        </div>
    <% end %>

    <div class="featured_projects">
            <%= render :partial => 'images/home_image_gallery' %>
    </div>

    <div class="homeSection quarter">

        <% if @community_activity_array.length > 0 %>
            <div class="activity">
                <span class="label" style="margin-bottom: 10px">Recent Questions</span><% if @community_activity_array.length >1 %><icon class="fa fa-refresh"></icon><% end %>
                <div class="activity_content"></div>
                <div class="byline"></div>
            </div>
            <hr>
        <% end %>

        <p class="label label-info"><%= ENV["APP_NAME"] %> News</p>
        <p class="view_all_link" style="margin-right: auto;"><%= link_to "View All", news_path %></p>
        <%= render :partial => "home/short_news" %>
    </div>

    <% if user_signed_in? %>
    <div class="latestActivities homeSection">
        <p class="label label-info">Your Activity Feed</p>
        <% if @activities.length != 0 %>
            <p class="view_all_link"><%= link_to "View All", activity_feed_index_path %></p>
        <% end %>

        <div class="home_activities" style="margin-top: 20px;">
            <% if @activities.length != 0 %>
                <% #list the last 4 news items %>
                <% @activities.first(5).each_with_index do |activity, index|%>
                    <% if activity.trackable != nil  %>
                        <% unless (render_activity activity).blank? || activity.is_private? %>
                            <div class="activity_feed_activity">
                                <%= render_activity activity %>
                            </div>
                            <hr>
                        <% end %>
                    <% end %>
                <% end %>
            <% else %>
                <% if current_user.following_users.count == 0 %>
                    <p id="no_activity">You have no items in your activity feed... yet!<br>
                        Try following someone!
                    </p>
                <% else %>
                    <p id="no_activity">No recent activity.  Tell your friends to come back to <%= ENV["APP_NAME"] %>!</p>
                <% end %>

            <% end %>
        </div>
    </div>
    <% end %>

    <div class="latestUpdates homeSection">
        <p class="label label-info ">Latest Updates</p>
        <p class="view_all_link"><%= link_to "View All Projects", projects_path %></p>
        <div style="clear: both;"></div>

        <div class="updates">
            <% #list the last 3 updated projects %>
            <% @latestProjects.each do |latestProject| %>
                <%= render :partial => 'projects/home_projects', :locals => {:project => latestProject, :source=> "home"} %>
            <% end %>
        </div>
    </div>

</div>

<script type="text/javascript">
$('.featureSlides .image').last().css('margin-bottom', '0px');
var community_activity = <%= raw @community_activity_array.to_json %>;
// console.log('community_activity: ' + community_activity);
var activity_index = 0;
var comments = <%= raw @comments_array.to_json %>;

$(document).ready(function(){
    cycleContent();
    
    $('.fa-refresh').click(function(){
       cycleContent();
    });
});

// pick a random question to display
function cycleContent(){
    activity_index++;
    if(activity_index >= community_activity.length){
        activity_index = 0;
    }
    // console.log('activity_index: ' + activity_index);

    var type = community_activity[activity_index][0];
    var description = community_activity[activity_index][1].substring(0,150).trim().replace(/(\r\n|\n|\r)/gm," ");
    var project_title = community_activity[activity_index][2];
    var project_id = community_activity[activity_index][3];
    var step_id = community_activity[activity_index][4];

    if(type == "question"){
        $('.activity').find('.label').removeClass('label-info').addClass('label-warning');
        $('.activity').find('.label').html('Recent Question');
    }else if(type == "comment"){
        $('.activity').find('.label').removeClass('label-warning').addClass('label-info');
        $('.activity').find('.label').html('Recent Comment');
    }

    var url = "<%=root_url.sub(/\/$/, '')%>"+"/projects/"+project_id+"/steps?step="+step_id;
    $('.activity_content').hide().html('<a href=' + url + '>"' + description + '"</a>').fadeIn();
    // http://0.0.0.0:3000/projects/3/steps?step=69
    $('.byline').hide().html('from <a href='+url+">"+project_title+"</a>").fadeIn();
}


</script>

app/views/home/mobile.html.erb
<style>
	.btn{
		float: right;
		font-size: 12px;
	}
</style>
<% title "Mobile Apps | #{ENV["APP_NAME"]}" %>
<div class="fullRow" style="width:940px">

	<div class="centeredContainer mobilePage">
		<h3><%= ENV["APP_NAME"] %> Mobile Apps</h3>	

		<div id="myCarousel" class="carousel slide">
		  <!-- Carousel items -->
		  <div class="carousel-inner">
		    <div class="active item" style="height: 350px"></div>
		  </div>
		  <!-- Carousel nav -->
		  <a class="carousel-control left" href="#myCarousel" data-slide="prev">&lsaquo;</a>
		  <a class="carousel-control right" href="#myCarousel" data-slide="next">&rsaquo;</a>
		</div>

		<div>
		<h6 style="text-align: center;"><%= ENV["APP_NAME"] %> mobile apps lets you create, update, and view your projects on-the-go. </h6>
		<ul style="margin-left: 200px; margin-top: 10px;">
			<li>Upload images and videos to your projects</li>
			<li>Create and update projects and steps</li>
			<li>View and rearrange steps in your Process Map</li>
		</ul>
		</div>
		<div style="clear: both;"></div>

		<hr>
		<div class="app_category" style="float: left; ">
			<div class="icon">
				<%= image_tag("mobile/android_icon.png") %>
			</div>
			<a href="#" style="margin-top: 10px; text-decoration: none;" class="btn btn-success" target="_blank">Get From Play Store</a>
		</div>

		<div class="app_category" style="float: right;">
			<div class="icon">
				<%= image_tag("mobile/apple_icon.png") %>
			</div>
			<%= link_to mobile_request_path do %>
				<a href="#" style="margin-top: 10px; text-decoration: none;" class="btn btn-info" target="_blank">Get from App Store</a>
			<% end %>
		</div>
		<div class="clear"></div>
		<hr>
	</div>

</div>

<script type="text/javascript">
$(document).ready(function(){
	$('.carousel').carousel({
	    interval: false
	});

	$('.carousel').on('slid', function() {
	    $('.carousel').carousel('pause');
	});
});
	
</script>

app/views/home/news.html.erb
<% title "News | #{ENV['APP_NAME']}" %>
<div class="fullRow" style="width:940px">

	

		<% website_project = Project.where(:title=>"Build in Progress Website").where(:remix_ancestry => nil).first() %>
		<% mobile_project = Project.where(:title=>"Build in Progress Mobile").where(:remix_ancestry => nil).first() %>


		<div class="centeredContainer newsPage">
			<div class="heading">
				<icon class="fa fa-bullhorn" style="font-size:30px;margin-top: 15px; margin-right:10px;"></icon><h3 style="margin-top: 0px;"><%= ENV["APP_NAME"] %> News</h3>
			</div>

			<% if website_project && mobile_project %>

				<div class="subheading">
					Find all the latest updates to <%= ENV["APP_NAME"] %> right here.  Check out the project pages for the <%= link_to "#{ENV["APP_NAME"]} Website", project_path(website_project), :class=>"project_link" %> and <%= link_to "#{ENV["APP_NAME"]} Mobile", project_path(mobile_project), :class=>"project_link" %> to give feedback!
				</div>

			<% end %>
		</div>


		<% News.order("created_at DESC").each do |news_item| %>
			<% news_item_step = Step.find(news_item.step_id) %>
			<div class="news_item">
				<div class="title"><span id="<%=news_item.id%>"></span><%= link_to news_item.title, project_steps_path(news_item_step.project, :step=>news_item.step_id) %></div>
				<div class="images">
					<% if news_item_step.images.where(:video_id => nil).count > 0 %>
						<%= link_to image_tag(news_item_step.images.where(:video_id => nil).order(:position).first.image_path_url(:preview)), project_steps_path(news_item_step.project, :step=>news_item.step_id)  %>
					<% end %>
				</div>
				<div class="description">
					<%= auto_link(news_item_step.description).html_safe %>
					<%= link_to "Comment", project_steps_path(news_item_step.project, :step=>news_item.step_id), :class=> "news_comment" %>
				</div>
				<div class="clear"></div>
				<div class="created_at"><%= news_item_step.created_at.strftime "%a %b %d at %I:%M %p"%></div>
			</div>
			<div class="clear"></div>
	<% end %>

<script>hljs.initHighlightingOnLoad();</script>

<style>
	pre{
		padding: 0;
	}
</style>

app/views/home/privacy_policy.html.erb
<% title "Privacy Policy | #{ENV["APP_NAME"]}" %>
<div class="fullRow" style="margin-top:50px;width:940px">
	<div class="centeredContainer" style="padding: 30px">
		<div class="textContainer" style="margin: 0px 50px">
		<h2 style="margin-bottom: 20px;">Privacy Policy</h2>

			<p>Intro about privacy policy goes here.</p>

			<br>

			<h4>What information do we collect?</h4>
			
			<h4>How do we use your information?</h4>

			<h4>How do we protect your information?</h4>

			<h4>Notifications of changes to the Privacy Policy</h4>
			
		</div>
	</div>
</div>